language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  # Install binary pandoc from Rstudio
  - export PATH="$HOME/pandoc:$PATH"
  - mkdir $HOME/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
      -d $HOME/pandoc
  - chmod +x $HOME/pandoc/pandoc
  - pandoc --version

  # Install jekyll
  - travis_retry gem install jekyll mime-types

  # Install R packages
  - ./travis-tool.sh r_binary_install rjsonio knitr png
  - ./travis-tool.sh r_install        lubridate microbenchmark testthat pryr
  - ./travis-tool.sh github_package   yihui/knitr rstudio/rmarkdown hadley/bookdown
  - mkdir ~/.R
  - cp Makevars ~/.R

script: jekyll build

after_success:
  - cp -r figures/ _site/figures

deploy:
  provider: s3
  access_key_id: AKIAJRIHBGWIWAZYFUFQ
  secret_access_key:
    secure: "c+2fsBiv47OpL/t7H4AKWB4zpNVNeZZ0Q/41ha48BlqZlgyoINcM1n2D4e0eWixpfSdxT0Uwtccv1rfb6eQj7lTvbz5aniPISobOa6+I4uRSNoAjCYh3BttBL55RFX8NXn9gL/H09kG3SyQ4Eu4By4FFUaPPa3zs5oiNIDYnRN0="
  bucket: r-pkgs.had.co.nz
  endpoint: r-pkgs.had.co.nz.s3-website-us-east-1.amazonaws.com
  local-dir: _site
  skip_cleanup: true
