language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

script:
- Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

before_cache:
- nvm install stable
- npm install netlify-cli -g

  script: netlify deploy --prod --dir _book
  skip_cleanup: true
deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$TRAVIS_COMMIT"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"